### ISSUE TITLE
Makefile code copying error

### ISSUE THREAD

**Issue by vigneshs-dev** [kingabzpro/Makefile-Actions#2]
Hi @kingabzpro ,
I am following the [GitHub Actions and MakeFile: A Hands-on Introduction](https://www.datacamp.com/tutorial/makefile-github-actions-tutorial). 

When I used the Makefile code given in the tutorial, I received the following error.
`makefile:5: *** missing separator.  Stop.`

After that, I used the raw file from your GitHub repository of this tutorial. Then only that error get solved. Please update that tutorial, so that others don't struggle in this place.

Thankyou.

**Comment by kingabzpro** [comment]
Thank you. But the code is same in both tutorial and GitHub repo.

**Comment by vigneshs-dev** [comment]
> Thank you. But the code is same in both tutorial and GitHub repo.

The code was same. But the error comes from Tab or Spaces in indentation in Makefile. If you have time, please look into that.
